### ISSUE TITLE
Nonsense Updated Timestamp

### ISSUE THREAD

**Issue by jmank88** [gochain-io/explorer#227]
The Genesis account is showing a nonsensical updated timestamp:
![screenshot_20190203-190845](https://user-images.githubusercontent.com/1194128/52185687-a8892680-27e7-11e9-8819-7cf02618e61a.png)
https://explorer.gochain.io/addr/0xf75b6e2d2d69da07f2940e239e25229350f8103f

**Comment by r-kononov** [comment]
Fixed on testnet, rolling out to mainnet - https://testnet-explorer.gochain.io/addr/0x2fe70f1df222c85ad6dd24a3376eb5ac32136978

**Comment by jmank88** [comment]
Has this been rolled out to mainnet already?

![screenshot from 2019-03-01 14-21-15](https://user-images.githubusercontent.com/1194128/53664160-622fb780-3c2d-11e9-9a0a-f4a23bfbb332.png)
From https://explorer.gochain.io/addr/0x65a0e277B2d0eEF62b8C30b280B4C49f83a104d3

**Comment by r-kononov** [comment]
I'll check if it's already on the mainnet, will update if needed

**Comment by jmank88** [comment]
Still seeing this:
![Screenshot from 2019-04-08 18-18-28](https://user-images.githubusercontent.com/1194128/55762978-db8ba880-5a2a-11e9-88a1-d6cdec0ee0fd.png)
https://testnet-explorer.gochain.io/addr/0x5c64a8af5F93304e7D39035955ED2E476FAA6b2f
